removed outdated info
aad-for-linux/openvpn-auth-aad pull request #2
Opened 2021-10-01 14:55 UTC by Ada-Codina

2021-10-01 20:22 UTC, oxr463 requested changes
Looks like we need a few changes. But first, can we rebase on master? Good work!

Reference(s):
- https://git-scm.com/book/en/v2/Git-Branching-Rebasing

2021-10-01 20:22 UTC, oxr463 commented on auth_aad.c
> + *  Copyright (C) 2019 Infinite Omicron, LLC. <open.source@infinite-omicron.com>
```suggestion
 *  Copyright (C) 2021 Infinite Omicron, LLC. <open.source@infinite-omicron.com>
```

2021-10-01 20:22 UTC, oxr463 commented on debian/changelog
> + -- Infinite Omicron, LLC. <open.source@infinite-omicron.com>  Wed, 19 Jun 2019 18:07:48 +0000
We don't need to change the changelog entries.

2021-10-01 20:22 UTC, oxr463 commented on debian/copyright
> +Copyright: 2019 Infinite Omicron, LLC. <open.source@infinite-omicron.com>
```suggestion
Copyright: 2021 Infinite Omicron, LLC. <open.source@infinite-omicron.com>
```

2021-10-05 14:03 UTC, Ada-Codina reviewed
reviewed

2021-10-05 20:27 UTC, closed without merging